### ISSUE TITLE
Совместимость?

### ISSUE THREAD

**Issue by miraserver** [kalbac/wc-edostavka#11]
Я что-то не совсем понял, то ли пдагин поддерживается, то ли нет. Если нет, как мы вроде как обсуждали, то что за обновления? Для кого?

Если да, то ни старая версия, ни новая у меня так и не заработала. Не указана точно совместимость ни wp ни wc. Например, у меня даже в настройках плагина город указать отправителя нельзя - не ищет ничего из выпадающего окна. Ну и сам плагин на сайте не показывается естественно

**Comment by antondrob** [comment]
У меня плагин Версия 1.3.2 работает

**Comment by miraserver** [comment]
у нас, увы, нет. Но, как я сказал, тут может есть зависимость от версии wp wc и другими установленными плагинами (конфликты). Хотелось бы уточнить, с кем и что протестировано и какие есть ограничения на совместимость...Может, проблема решается просто?

**Comment by rookees** [comment]
У меня не сохраняет настройки доставки - пишет такую ошибку

в базе вот так https://yadi.sk/i/dHbzP9wmvkzmc 

Strict Standards: Non-static method WC_Countries::get_base_country() should not be called statically, assuming $this from incompatible context in /var/www/.../wp-content/plugins/wc-edostavka-1.3.6/wc-edostavka.php on line 115

Что может быть не так ?

**Comment by kumatozz** [comment]
Такая же проблема.

**Comment by alexey13** [comment]
1.3.7 нет настроек плагина в woocommerce (просто отсутствует вкладка edostavka)

**Comment by kalbac** [comment]
@alexey13 а вы посмотрите повнимательней. Чудес не бывает. У всех есть а у вас почему то нету. Если у вас свежий вордпресс и вукомерц то всё должно быть.

**Comment by alexey13** [comment]
В том и дело что в настройках нет его. Достал следующим образом: создал новую зону и там выбрал edostavka. Она кликабельна

**Comment by kalbac** [comment]
@alexey13 Ну так и нужно было сделать. В новых версиях вукоммерц, сначала создаётся зона доставки, и потом уже к этой зоне подключаются нужные методы доставки.
