### ISSUE TITLE
Ru.php не найду

### ISSUE THREAD

**Issue by alexey13** [kalbac/wc-edostavka#14]
Добрый день! Не вижу этот файл. Про него в инструкции по установке написано. В директории плагина его нет и в папках тоже

**Comment by alexey13** [comment]
Понятно, похоже плагин не работает с последней версией woocommerce

**Comment by kalbac** [comment]
Данный плагин устарел, и на данный момент не поддерживается. Версия 1.3.2 работает со старыми версиями Woocommerce до 2.4 версии. В версиях где уже включены зоны доставки данный плагин не работает.
RU.php этот плагин не включён в состав с вервии 1.2 за не надобностью.

**Comment by alexey13** [comment]
Максим, сотрудничество с сдэк прекращено? А может на codecanyon опубликовать? Не хотят сдэк платить, но клиенты с радостью будут платить за этот плагин. Я в их числе. Без этого плагина очень неудобно.

**Comment by kalbac** [comment]
Алексей, всё будет... Будет и бесплатная версия и платная. Мне нужно время что бы с текущими проектами разобраться
