### ISSUE TITLE
Все равно нет метода доставки в корзине

### ISSUE THREAD

**Issue by e1sep0** [kalbac/wc-edostavka#15]
Добавил новую версию плагина, настройки в админке есть, но они не сохраняются почему то. И в корзине нет этого метода доставки

**Comment by not4u** [comment]
Адрес сайта дайте что бы посмотреть что там происходит.
Все правильно с зонами настроили?

**Comment by e1sep0** [comment]
С новой версией все заработало отлично. Спасибо вам большое!

**Comment by not4u** [comment]
Спасибо автору. Я такой же пользователь =)

**Comment by kalbac** [comment]
@not4u И вам спасибо, что помогаете пользователям моего плагина =))
