### ISSUE TITLE
Карта ПВЗ

### ISSUE THREAD

**Issue by vguns** [kalbac/wc-edostavka#27]
Подскажите, плагин умеет выводить ПВЗ на карте?

**Comment by vguns** [comment]
я ноль в java, но в файле edostavka.js ведь формируется какой-то массив вывода меток, или нет?

**Comment by kalbac** [comment]
да, плагин отображает пвз на карте яндекса

**Comment by vguns** [comment]
отключил saphali появилась спасибо

**Comment by kalbac** [comment]
Для спасибо есть ссылочка пожертвования в плагине ;)
