### ISSUE TITLE
Автоматическое определение города

### ISSUE THREAD

**Issue by vguns** [kalbac/wc-edostavka#28]
Подскажите как реализовать определение города покупателя и допустим, автозаполнение поля город, на странице checkout'а

**Comment by kalbac** [comment]
Если пользователь на сайте первый раз, то по умолчанию ему присваивается город отправитель (местоположение магазина). Как только пользователь выберет из списка город получатель, ему сразу же присваивается этот город.
Сам плагин автоматически не определяет местоположение пользователя. Однако в woocommerce есть функция определения ip адреса пользователя. А уже зная IP можно узнать и город.
Вот мой сервис для геотаргетинга http://woodev.ru/?geolocation_ip=213.180.193.3 (бесплатно)
Или вот ещё один очень хороший сервис https://suggestions.dadata.ru/suggestions/api/4_1/rs/detectAddressByIp?ip=213.180.193.3 (нужна авторизация количество запросов ограничено)

**Comment by vguns** [comment]
kalbac а можно в двух словах, вот я определил город посетителя как мне передать данные в плагин?
поидее мне надо получить id этого города у сдэка и уже id как то передать в плагин?

**Comment by vguns** [comment]
подскажите правильно ли будет сделать, я найду город через  http://woodev.ru/?geolocation_ip=213.180.193.3, найду для города CityCode в https://int.cdek.ru/pvzlist.php запишу этот код в сессию woocommerce как customer->state_id, а город как customer->state, то плагин wc-edostavka будет показывать текущий город и пункты в нем при первом заходе в chekout, мне важно чтобы  покупателю сразу показывались  данные о доставке в его город.

**Comment by kalbac** [comment]
@vguns да, ход ваших мыслей правильный. Основная задача, это получить ID города, а не его название.
