### ISSUE TITLE
Установка определенной суммы по доставке для конкретного города

### ISSUE THREAD

**Issue by theabbd** [kalbac/wc-edostavka#3]
Здравствуйте. Будет ли в след. версиях возможность установить определенную сумму (или вычитать / делать наценку) при доставке для определенных городов? 
Например, сделать -175 р. на доставку от предлагаемой цены только для Москвы и Спб, а для все остальных городов пускай берет информацию с серверов Сдека ? 
Есть ли такая возможность вообще или даже не стоит такое ожидать?
Заранее спасибо.

**Comment by kalbac** [comment]
Здравствуйте.
Теоретически это возможно, но в ближайших релизах этого не предвидится.
