### ISSUE TITLE
Elder version

### ISSUE THREAD

**Issue by Kazimkudesnik** [kalbac/wc-edostavka#33]
Здравствуйте!
У меня ВП версии 4.6.3, wocommerce 2.4.12
При установке плагина не работает страница оформления заказа. При обновлении ВП и ВК не появляется в настройках плагин (точнее в плагинах он появляется, а в настройках доставки - нет). И с зонами доставки при обновлении ВК не очень понятно.
Я так понимаю это конфликт версий 
"Для версии плагина ниже 1.3.2

Wordpress не ниже 4.2
Woocommerce не ниже 2.3
PHP не ниже 5.3
Для версии плагина выше 1.3.6

Wordpress не ниже 4.6
Woocommerce не ниже 2.5.4
PHP не ниже 5.3"

Как можно получить плагин верссии 1.3.2 или ниже?

**Comment by kalbac** [comment]
https://github.com/kalbac/wc-edostavka/releases

**Comment by Kazimkudesnik** [comment]
Спасибо большое!
