### ISSUE TITLE
Бесплатная доставка + ПВЗ

### ISSUE THREAD

**Issue by anfisabreus** [kalbac/wc-edostavka#34]
Прежде всего спасибо за классный плагин. 
Есть вопрос. Я использую в своем магазине дополнительные метод доставки "Бесплатная доставка" (сумма минимального заказа). При достижении определенной суммы заказа появляется Бесплатная доставка.  

Можно ли сделать так, чтобы при методе "Бесплатная доставка" оставался выбор ПВЗ, поскольку отправлять заказ мы будем компанией Сдэк, просто с клиента за доставку деньги не берем?

**Comment by kalbac** [comment]
@anfisabreus Это индивидуальная доработка, она платная. Вопросы на почту maksim@martirosoff.ru
