### ISSUE TITLE
Перестали отображаться пункты самовывоза в г. Москва

### ISSUE THREAD

**Issue by dimsonbgg** [kalbac/wc-edostavka#45]
Добрый вечер господа. Из списка можно выбрать пункты самовывоза, но почему-то перестали отображаться пункты самовывоза на карте по городу Москва. В любых других городах все работает замечательно, а вот по Москве, карта Яндекс абсолютно пустая. 
У кого нибудь наблюдается такая проблема?!

Вот наш интернет-магазин: https://caffevita.ru

**Comment by ghost** [comment]
Такая же ерунда. Надо писать в СДЭК. У них там бывают косяки. Одно время один из пунктов в СПб "находился" в Иране, а поскольку карта масштабируется так, чтобы включать все пункты, выглядела она странно и неудобно.

**Comment by kalbac** [comment]
Здравствуйте. Я уже связался со службой технической поддержки СДЭК. "Косяк" на их стороне. В списке ПВЗ у одного из ПВЗ (На авиамоторной) допущена ошибка в атрибуте. Из за этого скрипт прекращает работу и не выводит список на карту.
Они обещали исправить в ближайшее время.
Как только они исправят, карта заработает сама собой.

**Comment by ghost** [comment]
Максим, у меня вопрос по версии для 3.0. В вашем демо вообще нет пунктов самовывоза. Если приобрести новый плагин у вас, они там будут?

**Comment by kalbac** [comment]
Как это нету? На демо сайте включены два тарифа, "Посылка дверь-дверь" и "Посылка дверь-склад", но переименованы по другому. Если выбрать город Воронеж, то вообще отобразится тариф "Доставка по Воронежу" и так можно сделать для любого города. (в самой новой версии. её ещё нету в продаже)

**Comment by ghost** [comment]
А, понятно, то есть я не видел пунктов в Москве как раз из-за этого глюка, выходит он уже очень давно...

**Comment by kalbac** [comment]
ну не очень давно. Где то неделю как. Но на демо сайте сейчас и Москва тоже работает.
