### ISSUE TITLE
Бредовая стоимость доставки в корзине/оформлении

### ISSUE THREAD

**Issue by vdementev** [kalbac/wc-edostavka#46]
Неверно показывает стоимость доставки в корзине/оформлении заказа. Независимо от того какие товары кладём, стоимость отличается в разы в большую сторону. Судя по логам от СДЕК приходят правильные цифры, они сходятся с их калькулятором. Что делать? Куда копать?

Вот что приходит от СДЕК:

08-11-2017 @ 13:24:35 - Параметры запроса: Array
(
    [tariffs] => Array
        (
            [0] => 136
            [1] => 137
        )

    [login] => ***
    [password] => ***
    [sender_city] => 44
    [receiver_city] => 44
)

08-11-2017 @ 13:24:35 - Вес и объём для каждого товара: Array
(
    [0] => Array
        (
            [height] => 3
            [width] => 10
            [length] => 10
            [weight] => 0.025
        )

)

08-11-2017 @ 13:24:36 - Ответ на запрос тарифа [Посылка склад-склад]
08-11-2017 @ 13:24:36 - Сервер СДЭК вернул результат: Array
(
    [price] => 147.5
    [deliveryPeriodMin] => 1
    [deliveryPeriodMax] => 1
    [deliveryDateMin] => 2017-08-14
    [deliveryDateMax] => 2017-08-14
    [tariffId] => 136
    [priceByCurrency] => 147.5
    [currency] => RUB
)

08-11-2017 @ 13:24:36 - Ответ на запрос тарифа [Посылка склад-дверь]
08-11-2017 @ 13:24:36 - Сервер СДЭК вернул результат: Array
(
    [price] => 312.7
    [deliveryPeriodMin] => 1
    [deliveryPeriodMax] => 1
    [deliveryDateMin] => 2017-08-14
    [deliveryDateMax] => 2017-08-14
    [tariffId] => 137
    [priceByCurrency] => 312.7
    [currency] => RUB
)

А вот скриншот со страницы оформления заказа:
![2017-08-11](https://user-images.githubusercontent.com/14889996/29210093-7ee3ede4-7e9a-11e7-817d-23f7e0fc5942.png)

**Comment by kalbac** [comment]
1) Видно, что скорей всего у вас установлена надбавочная стоимость за доставку.
2) Проблема с определением "плавающей" точки
Вариант решения: в файле class-wc-shipping-edostavka.php в методе `get_rates` есть две переменные `$cost` и `$fee`, значение которых обвёрнуты методом `fix_format` вот этот метод нужно удалить. Т.е. Сделать так `$cost = esc_attr( $price ); $fee  = $this->get_fee( $this->fee, $cost );`

**Comment by vdementev** [comment]
1. Добавочной стоимости нет;
2. Помогло! Теперь считается правильно. Стоимость доставки от СДЕК плюс НДС.

Спасибо!
