### ISSUE TITLE
Отключается плагин СДЭК при покупке свыше 28 тысяч рублей

### ISSUE THREAD

**Issue by dimsonbgg** [kalbac/wc-edostavka#48]
Вечер добрый! Сегодня заметил проблему с плагином СДЭК, он отключается полностью при единоразовой покупке на сайте свыше 28 тысяч рублей. Кто нибудь сталкивался с данной проблемой?!

**Comment by kalbac** [comment]
Здравствуйте. Что вы имеете ввиду "плагин отключается полностью"? Он перестаёт работать вообще? Ограничений на сумму покупки в плагине нету.
1) Включите режим отладки и посмотрите что написано в логах.
2) Убедитесь что общий вес и габариты данного заказа в ходят в допустимые значения габаритов для используемых вами тарифов. Попробуйте включить тариф "Магистральный экспресс" (если не включён), у этого тарифа габариты посылки могут быть очень большими.

**Comment by dimsonbgg** [comment]
Точно, спасибо большое за оперативность. От 30 кг нужно использовать тариф экспресс тяжеловесы склад склад, а при покупке кофемашины были не верно указаны габариты.
