### ISSUE TITLE
Проблема с отображением на разных браузерах

### ISSUE THREAD

**Issue by blacksheep581** [kalbac/wc-edostavka#49]
Возникла проблема с плагином СДЭК. Все настроили корректно, все и везде добавили, но у одних людей на странице оформления заказа отображены все методы доставки и все работает правильно, а у других пишет, что нет доступных методов доставки. Пробовали с разных браузеров, в одном браузере например есть проблема, а в другом нету и т.д

Причем программист который настраивает плагин в недоумении - с его компьютера и с его браузеров все показывается. У меня и друзей - нет.

С чем может быть связана проблема?

**Comment by kalbac** [comment]
Надпись "Нет доступных методов" означает, что либо по данному направлению реально нету доступных тарифов при заданных условиях либо что то вызывает ошибку (что мало вероятно, так как вы говорите что у всех работает кроме вас и ваших друзей). Браузеры тут не причём по сути. Так как сам плагин не работает с клиентской частью (кроме отображения карты ПВЗ). Всё остальное делает сам вукоммерц.
Включите режим отладки, и посмотрите какие ответы возвращает сервер СДЭК.

**Comment by blacksheep581** [comment]
Поняли в чем ошибка была - плагин отображает доставку на вариативных и не отображает на простых товарах. Причем если в заказе есть и вариативный и простой товар, доставка показывается. В чем может быть проблема?

**Comment by kalbac** [comment]
Включите режим отладки. Смотрите что пишет лог.

**Comment by blacksheep581** [comment]
Все верно! Проблема оказалась в том что у нас для всех простых продуктов WooCommerce брал вес 5915753 то есть более тысячи тонн) Мы поставили так чтобы в приоритете был дефолтный вес указанный в настройках плагина СДЭК и все встало на свои места.
