### ISSUE TITLE
Не верно считает (а в некоторые направления вообще не считает) стоимость доставки

### ISSUE THREAD

**Issue by Baron4eg** [kalbac/wc-edostavka#5]
Проблема в следующем:
Плагин не правильно считает (а иногда вообще не считает) стоимость доставки. Скриншоты во вложении.

Первый раз столкнулись с проблемой при попытке установить плагин на наш основной сайт, но столкнувшись с этой проблемой. Стали разбираться, но проблем с сайтом выявлено не было. 
Решили пойти другим путём: создали новый сайт (другой хостинг, другой шаблон, последняя версия wordpress и woocommerce) и на этот новый сайт установили Ваш модуль. Проблема повторилась. Плагин так же не верно считает стоимость доставки, а иногда сообщает что в выбранный город вообще нет доставки, хотя через онлайн калькулятор на сайте курьерской службы всё считается верно и доставка туда осуществляется. 

[edostavka.zip](https://github.com/kalbac/wc-edostavka/files/222287/edostavka.zip)

**Comment by kalbac** [comment]
Данная проблема была связана из-за изменения ответа от сервера СДЕК. Удалите старую версию, скачайте и установите последнюю версию https://github.com/kalbac/wc-edostavka/releases/latest 
Ознакомитесь с описанием релиза.
