### ISSUE TITLE
Edostavka (СДЭК) фатальная ошибка после активизации

### ISSUE THREAD

**Issue by profitan** [kalbac/wc-edostavka#55]
После активизации плагина выходит ошибка

Fatal error: Call to undefined method WC_Edostavka_Shipping_Method::get_field_key() in /var/www/u0508350/data/www/profitan.ru/wp-content/plugins/wc-edostavka-1.4.1/includes/class-wc-shipping-edostavka.php on line 204

Как решить проблему?

**Comment by kalbac** [comment]
Какая версия вашего WC?
Версия плагина 1.4.1 не работает с Woocommerce 3+ версиями.
Читайте описание https://github.com/kalbac/wc-edostavka#%D0%9E%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5

**Comment by profitan** [comment]
Версия WC 2.3.7


>Среда, 23 мая 2018, 11:50 +03:00 от Максим Мартиросов <notifications@github.com>:
>
>Какая версия вашего WC?
>Версия плагина 1.4.1 не работает с Woocommerce 3+ версиями.
>Читайте описание  https://github.com/kalbac/wc-edostavka#%D0%9E%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

С уважением,
Анна Сизова
anna@profitan.ru
https://profitan.ru
Tel., Vaiber, WhatsApp  +7 911 971 3896
+7 931 353 7044

**Comment by kalbac** [comment]
@profitan У вас очень старая версия WC. Для этой версии могут (но это не точно) подойти версии плагина [WC eDostavka 1.3.2](https://github.com/kalbac/wc-edostavka/releases/tag/1.3.2)

**Comment by profitan** [comment]
1.3.2 не пошла. Установила 1.3.0  при тестовом оформлении заказа выдает ошибку:  

Fatal error: Call to a member function get_id() on array in /var/www/u0508350/data/www/profitan.ru/wp-content/plugins/woo-cdek/inc/class-cdek-shipping-method.php on line 128

С чем это может быть связано? Сайт еще не выложен и не привязан домен, т.к. планирую его перенос после настройки всех функций

**Comment by profitan** [comment]
установила 1.2.6  - 1.3.0 тоже не пошла. извините - запуталась

**Comment by kalbac** [comment]
@profitan Я вообще не понимаю зачем вы используете такую старую версию Woocommerce. Тем более если сайт ещё и не на продакшене. Вам всё равно придётся рано или поздно обновится и лучше это сделать сейчас.
Что касается плагина WC eDostavka 1.4.0 версий (бесплатных версий) то они более не поддерживаются. Не из-за того что они бесплатны, а потому что они уже не актуальны. 
Если вы не хотите обновляться и покупать платную версию плагина, то могу вам посоветовать просто побывать устанавливать все версии, начиная с самой первой.

**Comment by profitan** [comment]
я хочу обновиться, но не знаю как это сделать. Я взяла готовую тему wordpress и сломала весь мозг за две недели

**Comment by kalbac** [comment]
@profitan напишите мне на почту maksim@martirosoff.ru
Тему закрываю.
