### ISSUE TITLE
При автозаполнении в Safari форма не валидна так как поле "Город" не заполняется и не даёт себя редактрировть после.

### ISSUE THREAD

**Issue by mihrich** [kalbac/wc-edostavka#56]
Проверено в мобильном  Safari

**Comment by kalbac** [comment]
Какая версия плагина СДЭК и Woocommerce?
Версии ниже 1.4.2 не поддерживаются уже года 2.

**Comment by mihrich** [comment]
WP - версия 5.5.1
WooCommerce - Версия 3.6.2
CDEK WooCommerce Shipping Method - Версия 2.1.5

Проблема обнаруживается, в основном в мобильной версии Chrome, Safari

Ошибка "плавающая" то есть, то нет.
Когда человек отдельно авто заполняет поля формы, то бывает два варианта ошибок:
1. все поля заполняются, а поле "Город" нужно выбрать из списка, но после попытки отправки формы выводится ошибка "Поле адрес является обязательным полем"
2. Все поля заполняются, но поле "Город" не выбирается  оно неактивно и заблокировано. И соответственно нельзя отправить форму.

![1](https://user-images.githubusercontent.com/1442402/56897253-b07afe80-6a96-11e9-870d-2f5c8e3b2f29.jpeg)
![2](https://user-images.githubusercontent.com/1442402/56897255-b07afe80-6a96-11e9-898f-c70f3c15ca8e.jpeg)

**Comment by mihrich** [comment]
Включил / выключил плагин, ошибка исчезла, возможно очистился кэш. По крайней мере ошибка больше не повторяется, похоже можно закрывать задачу.
