### ISSUE TITLE
Показать карту ПВЗ по шорткоду

### ISSUE THREAD

**Issue by not4u** [kalbac/wc-edostavka#7]
Добрый день. Подскажите насколько сложно реализовать возможность показать карту ПВЗ на отдельной странице? Например было бы очень удобно на информационной странице Доставка вставить шорткод например [wc_edostavka] и на странице показалась бы карта и выбор города. Выбираешь город и вуаля. Вот все пункты выдачи.

**Comment by vguns** [comment]
да присоединяюсь, как можно вывести карту с пвз на отдельной странице

**Comment by kalbac** [comment]
В самом плагине это не реализовано и не планировалось (как минимум в бесплатной версии)
